name: Sync upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间午夜运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4 # 升级到 v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }} # 显式传递 Token
          persist-credentials: true # 保持认证信息

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/cmliu/edgetunnel.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          # 尝试合并，若冲突则终止（可替换为强制合并策略）
          git merge --no-edit upstream/main || exit 1
          git push origin main
      - name: Notify on failure
        if: failure()
        uses: actions/notifications@v1
        with:
          type: slack
          message: "上游同步失败：${{ github.repository }}"